### ISSUE TITLE
ivy-mode not enabled on startup

### ISSUE THREAD

**Issue by dsbahr** [daviwil/emacs-from-scratch#51]
Hi there, 

Thanks for this great series. When I start emacs with your init.el based on episode #1, ivy-mode does not get toggled automatically. I need to toggle ivy-mode through M-x before its enabled. 

Shouldn't  it be enabled by default on startup or am I doing something wrong? I have used the init.el from your repo so I shouldn't have any differences on my side and I'm running emacs 27.1.

**Comment by jtepe** [comment]
Hi,

the problem here is that `use-package` defers loading `ivy`, and the therefore executing `:config`, until `ivy` is actually required. Doing a `C-s C-f` directly after starting Emacs won't show you the `ivy`-enhanced minibuffer, as `ivy-mode 1` hasn't run yet. You could `C-s` to trigger the keybinding for `swiper` to enable `ivy-mode`, or you could add a `:demand` to the `use-package` form like this
```elisp
(use-package ivy
  :diminish
  :demand
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)	
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config (ivy-mode 1))
```

@daviwil might know better which option to choose here. I am also still a beginner and following along :).

**Comment by daviwil** [comment]
Hi @dsbahr, sorry for the trouble!  @jtepe is correct, adding `:demand` to the `use-package` expression will cause Ivy to be loaded and started when Emacs starts up.
